In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2], [3, 4]  ])
B = np.array([[5, 6], [7, 8]])
print(A)
print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [3]:
np.dot(A, B)


array([[19, 22],
       [43, 50]])

In [4]:
A@B

array([[19, 22],
       [43, 50]])

In [5]:
A.T

array([[1, 3],
       [2, 4]])

In [6]:
B.T

array([[5, 7],
       [6, 8]])

In [7]:
np.transpose(A)

array([[1, 3],
       [2, 4]])

In [8]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [9]:
np.linalg.det(A)

np.float64(-2.0000000000000004)

In [11]:
b = np.array([9, 8])
x = np.linalg.solve(A, b)
print(x)

[-10.    9.5]


In [13]:
eigenvalores, eigenvectores = np.linalg.eig(A)

In [14]:
eigenvalores


array([-0.37228132,  5.37228132])

In [15]:
eigenvectores

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

In [19]:
U, S, V = np.linalg.svd(A)
print(U)
print(S)
print(V)

[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
[5.4649857  0.36596619]
[[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]
