In [1]:
import numpy as np

In [2]:
file_path = "../../data/matriz3x3.txt"
data = np.loadtxt(file_path)
data

array([[1.   , 0.674, 0.392],
       [0.183, 1.   , 0.729],
       [0.438, 0.255, 1.   ]])

In [4]:
type(data[0,0])
np.float64

data[0,0]

np.float64(1.0)

In [5]:
file_path = "../../data/matriz10x10.txt"
data = np.loadtxt(file_path)
data

array([[1.        , 0.891773  , 0.96366276, 0.38344152, 0.79172504,
        0.52889492, 0.56804456, 0.92559664, 0.07103606, 0.0871293 ],
       [0.0202184 , 1.        , 0.77815675, 0.87001215, 0.97861834,
        0.79915856, 0.46147936, 0.78052918, 0.11827443, 0.63992102],
       [0.14335329, 0.94466892, 1.        , 0.41466194, 0.26455561,
        0.77423369, 0.45615033, 0.56843395, 0.0187898 , 0.6176355 ],
       [0.61209572, 0.616934  , 0.94374808, 1.        , 0.3595079 ,
        0.43703195, 0.6976312 , 0.06022547, 0.66676672, 0.67063787],
       [0.21038256, 0.1289263 , 0.31542835, 0.36371077, 1.        ,
        0.43860151, 0.98837384, 0.10204481, 0.20887676, 0.16130952],
       [0.65310833, 0.2532916 , 0.46631077, 0.24442559, 0.15896958,
        1.        , 0.65632959, 0.13818295, 0.19658236, 0.36872517],
       [0.82099323, 0.09710128, 0.83794491, 0.09609841, 0.97645947,
        0.4686512 , 1.        , 0.60484552, 0.73926358, 0.03918779],
       [0.28280696, 0.12019656, 0.2961402

In [8]:
file_path = "../../data/matriz10x10.txt"
data10x10 = np.genfromtxt(file_path)
data10x10

array([[1.        , 0.891773  , 0.96366276, 0.38344152, 0.79172504,
        0.52889492, 0.56804456, 0.92559664, 0.07103606, 0.0871293 ],
       [0.0202184 , 1.        , 0.77815675, 0.87001215, 0.97861834,
        0.79915856, 0.46147936, 0.78052918, 0.11827443, 0.63992102],
       [0.14335329, 0.94466892, 1.        , 0.41466194, 0.26455561,
        0.77423369, 0.45615033, 0.56843395, 0.0187898 , 0.6176355 ],
       [0.61209572, 0.616934  , 0.94374808, 1.        , 0.3595079 ,
        0.43703195, 0.6976312 , 0.06022547, 0.66676672, 0.67063787],
       [0.21038256, 0.1289263 , 0.31542835, 0.36371077, 1.        ,
        0.43860151, 0.98837384, 0.10204481, 0.20887676, 0.16130952],
       [0.65310833, 0.2532916 , 0.46631077, 0.24442559, 0.15896958,
        1.        , 0.65632959, 0.13818295, 0.19658236, 0.36872517],
       [0.82099323, 0.09710128, 0.83794491, 0.09609841, 0.97645947,
        0.4686512 , 1.        , 0.60484552, 0.73926358, 0.03918779],
       [0.28280696, 0.12019656, 0.2961402

In [ ]:
file_path3c = "../../data/matriz3x3_comment01.txt"
data3c = np.loadtxt(file_path3c, comments="#")
data3c

array([[1.   , 0.674, 0.392],
       [0.183, 1.   , 0.729],
       [0.438, 0.255, 1.   ]])

In [ ]:
file_path3c = "../../data/matriz3x3_comment01.txt"
data3c = np.loadtxt(file_path3c, skiprows=1)
data3c

In [13]:
file_pathNaN = "../../data/matriz3x3_faltantes.txt"
dataNaN = np.genfromtxt(file_pathNaN,  filling_values=0)
dataNaN

array([[1.   , 0.674, 0.392],
       [0.183, 0.   , 0.729],
       [0.438, 0.255, 1.   ]])