In [4]:
import numpy as np

In [5]:
np.__version__

'2.3.2'

In [7]:
a = np.array([1, 2, 3])
type(a)

np.ndarray

a1 = np.array([[1, 2, 3], [4, 5, 6]])

a  + a1


array([[2, 4, 6],
       [5, 7, 9]])

In [10]:
a2 = np.array(
    [
        [1,2,3,4],
        [5,6,7,8]
    ]
)

a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
lista = [[1, 2, 3, 4], [5, 6, 7, 8]]
array = np.array(lista)
array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])