In [1]:
import numpy as np

In [4]:
m = np.arange(15).reshape(3, 5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
m.reshape(5,-1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [6]:
m.reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
m = np.random.randint(0, 10, (3, 3))

In [10]:
m.reshape(-1)

array([9, 3, 0, 4, 1, 4, 5, 5, 6], dtype=int32)

In [12]:
m = np.random.rand(100,100,3)
m

array([[[0.8969849 , 0.5658466 , 0.45492222],
        [0.6277783 , 0.70964923, 0.05405017],
        [0.45512196, 0.1694254 , 0.95476872],
        ...,
        [0.858791  , 0.94399694, 0.39777558],
        [0.6428687 , 0.83787375, 0.77683611],
        [0.30551262, 0.28573262, 0.62792454]],

       [[0.73350133, 0.34987   , 0.85103294],
        [0.48399074, 0.26822639, 0.11614786],
        [0.99195478, 0.97602495, 0.58550849],
        ...,
        [0.17626287, 0.85711084, 0.16722882],
        [0.40928116, 0.60939448, 0.95771644],
        [0.04700989, 0.20821367, 0.29607008]],

       [[0.36077684, 0.44607206, 0.18815044],
        [0.43017381, 0.94850839, 0.99045374],
        [0.17411089, 0.75049522, 0.29878627],
        ...,
        [0.28944829, 0.82368026, 0.94138157],
        [0.65762168, 0.42848027, 0.96141508],
        [0.99633968, 0.01440668, 0.27337847]],

       ...,

       [[0.11572706, 0.02484596, 0.84285131],
        [0.22733848, 0.93829353, 0.02612827],
        [0.01430957, 0

In [14]:
n = m.reshape(-1,3)
n.shape
n

array([[0.8969849 , 0.5658466 , 0.45492222],
       [0.6277783 , 0.70964923, 0.05405017],
       [0.45512196, 0.1694254 , 0.95476872],
       ...,
       [0.56307394, 0.28290638, 0.50739847],
       [0.75978678, 0.00409103, 0.04188369],
       [0.60202833, 0.19459936, 0.27903338]], shape=(10000, 3))

In [15]:
m.reshape(10,2)

ValueError: cannot reshape array of size 30000 into shape (10,2)

In [16]:
np.resize(m, (10,2))

array([[0.8969849 , 0.5658466 ],
       [0.45492222, 0.6277783 ],
       [0.70964923, 0.05405017],
       [0.45512196, 0.1694254 ],
       [0.95476872, 0.13822932],
       [0.09558941, 0.73413205],
       [0.88782189, 0.40166199],
       [0.5694118 , 0.91469047],
       [0.75383509, 0.47375758],
       [0.68058293, 0.35028664]])