In [1]:
import numpy as np

In [2]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [5]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
np.full((3,3),-1)

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [7]:
np.random.rand(3, 3)

array([[0.83415355, 0.97635436, 0.99079837],
       [0.68010424, 0.91490748, 0.58941892],
       [0.55351502, 0.84534372, 0.78441479]])

In [9]:
np.random.randint(0, 10, (10, 10))

array([[4, 4, 3, 5, 7, 0, 6, 1, 7, 3],
       [1, 0, 3, 0, 5, 9, 7, 8, 9, 2],
       [2, 2, 3, 7, 9, 0, 5, 4, 3, 2],
       [3, 4, 6, 6, 2, 6, 2, 3, 3, 3],
       [3, 3, 2, 4, 6, 1, 8, 9, 6, 4],
       [0, 9, 1, 2, 4, 7, 4, 5, 7, 7],
       [5, 6, 7, 9, 9, 9, 8, 2, 3, 1],
       [5, 6, 1, 9, 1, 6, 3, 1, 3, 2],
       [0, 3, 0, 8, 9, 9, 3, 1, 8, 0],
       [2, 2, 8, 3, 1, 1, 0, 0, 2, 4]], dtype=int32)

In [ ]:
unos = np.ones((3, 3))
azar = np.random.randint(0, 3, (3, 3))

unos.shape

(3, 3)

In [15]:
unos + azar

array([[3., 1., 2.],
       [3., 3., 1.],
       [2., 1., 1.]])

In [16]:
unos += 2
unos

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [19]:
azar *= azar
azar

array([[16,  0,  1],
       [16, 16,  0],
       [ 1,  0,  0]], dtype=int32)