In [1]:
import numpy as np

In [5]:
file_path = '../../data/m10x10_int.txt'
data = np.loadtxt(file_path) 
data

array([[6., 0., 8., 5., 2., 0., 5., 7., 9., 3.],
       [7., 3., 1., 8., 6., 0., 6., 2., 7., 2.],
       [7., 6., 3., 5., 5., 0., 5., 8., 5., 5.],
       [7., 3., 3., 9., 3., 3., 8., 1., 9., 7.],
       [0., 3., 0., 7., 0., 4., 3., 7., 4., 9.],
       [4., 8., 8., 3., 7., 4., 5., 7., 4., 3.],
       [2., 6., 6., 8., 9., 9., 7., 9., 6., 5.],
       [4., 9., 9., 9., 1., 8., 6., 9., 8., 9.],
       [5., 8., 6., 8., 4., 8., 2., 7., 8., 7.],
       [5., 8., 5., 7., 7., 3., 4., 3., 5., 6.]])

In [7]:
data.shape

(10, 10)

In [8]:
data[:2]

array([[6., 0., 8., 5., 2., 0., 5., 7., 9., 3.],
       [7., 3., 1., 8., 6., 0., 6., 2., 7., 2.]])

In [10]:
data[:8,4:-1]

array([[2., 0., 5., 7., 9.],
       [6., 0., 6., 2., 7.],
       [5., 0., 5., 8., 5.],
       [3., 3., 8., 1., 9.],
       [0., 4., 3., 7., 4.],
       [7., 4., 5., 7., 4.],
       [9., 9., 7., 9., 6.],
       [1., 8., 6., 9., 8.]])

In [12]:
data333 = np.random.randint(0,10,(3,3,3))
data333

array([[[4, 8, 7],
        [7, 8, 8],
        [6, 2, 2]],

       [[6, 5, 2],
        [2, 2, 3],
        [0, 5, 3]],

       [[2, 8, 8],
        [8, 9, 6],
        [1, 4, 6]]], dtype=int32)

In [13]:
data333[:,:,:]

array([[[4, 8, 7],
        [7, 8, 8],
        [6, 2, 2]],

       [[6, 5, 2],
        [2, 2, 3],
        [0, 5, 3]],

       [[2, 8, 8],
        [8, 9, 6],
        [1, 4, 6]]], dtype=int32)

In [14]:
data333[0,:,:]

array([[4, 8, 7],
       [7, 8, 8],
       [6, 2, 2]], dtype=int32)

In [15]:
data333[:,2,:]

array([[6, 2, 2],
       [0, 5, 3],
       [1, 4, 6]], dtype=int32)

In [16]:
matriz = np.random.randint(0,10,(15,15))
matriz

array([[4, 8, 4, 3, 4, 5, 5, 0, 0, 8, 3, 7, 6, 7, 2],
       [8, 3, 0, 7, 6, 8, 7, 8, 7, 1, 5, 2, 1, 0, 2],
       [3, 8, 3, 4, 2, 7, 3, 7, 2, 5, 3, 5, 2, 6, 5],
       [4, 7, 0, 5, 3, 3, 4, 6, 9, 8, 0, 3, 7, 7, 4],
       [8, 1, 0, 0, 2, 4, 8, 6, 3, 7, 4, 9, 9, 8, 6],
       [9, 0, 3, 4, 9, 9, 4, 4, 8, 6, 7, 9, 3, 1, 2],
       [5, 3, 4, 4, 4, 4, 6, 1, 4, 8, 4, 3, 7, 6, 1],
       [4, 8, 3, 0, 4, 6, 0, 0, 1, 2, 1, 3, 3, 2, 1],
       [0, 7, 3, 4, 9, 1, 3, 7, 5, 9, 9, 3, 4, 0, 0],
       [0, 8, 0, 8, 0, 2, 1, 2, 8, 9, 1, 8, 1, 3, 0],
       [8, 2, 0, 1, 5, 4, 0, 6, 8, 8, 5, 4, 5, 6, 8],
       [0, 4, 4, 0, 4, 9, 4, 5, 1, 5, 4, 0, 9, 0, 0],
       [0, 5, 3, 8, 3, 8, 7, 0, 4, 0, 5, 3, 6, 6, 7],
       [2, 0, 1, 4, 1, 9, 5, 2, 2, 1, 0, 8, 5, 0, 8],
       [9, 8, 7, 6, 4, 9, 1, 0, 9, 2, 7, 5, 7, 9, 7]], dtype=int32)

In [18]:
matriz[:,::3]

array([[4, 3, 5, 8, 6],
       [8, 7, 7, 1, 1],
       [3, 4, 3, 5, 2],
       [4, 5, 4, 8, 7],
       [8, 0, 8, 7, 9],
       [9, 4, 4, 6, 3],
       [5, 4, 6, 8, 7],
       [4, 0, 0, 2, 3],
       [0, 4, 3, 9, 4],
       [0, 8, 1, 9, 1],
       [8, 1, 0, 8, 5],
       [0, 0, 4, 5, 9],
       [0, 8, 7, 0, 6],
       [2, 4, 5, 1, 5],
       [9, 6, 1, 2, 7]], dtype=int32)

In [19]:
matriz[[0,3]]

array([[4, 8, 4, 3, 4, 5, 5, 0, 0, 8, 3, 7, 6, 7, 2],
       [4, 7, 0, 5, 3, 3, 4, 6, 9, 8, 0, 3, 7, 7, 4]], dtype=int32)

In [20]:
matriz[:,[0,3]]

array([[4, 3],
       [8, 7],
       [3, 4],
       [4, 5],
       [8, 0],
       [9, 4],
       [5, 4],
       [4, 0],
       [0, 4],
       [0, 8],
       [8, 1],
       [0, 0],
       [0, 8],
       [2, 4],
       [9, 6]], dtype=int32)